### ISSUE TITLE
CentOS 5 Docker image wrong /etc/yum.repos.d/CentOS-Sources.repo

### ISSUE THREAD

**Issue by tukiyo** [CentOS/sig-cloud-instance-images#18]

**Comment by tukiyo** [comment]
I tried 

```
docker run -it centos:centos5 /bin/bash
```

```
yum install yum-utils
yumdownloader --source php
```

then, error occured.

```
Loaded plugins: etckeeper, fastestmirror
Determining fastest mirrors
 * base: ftp.tsukuba.wide.ad.jp
 * extras: ftp.tsukuba.wide.ad.jp
 * libselinux: ftp.tsukuba.wide.ad.jp
 * updates: ftp.tsukuba.wide.ad.jp
base                                                                                              | 1.1 kB     00:00     
base/primary                                                                                      | 1.3 MB     00:00     
base                                                                                                           3667/3667
extras                                                                                            | 2.1 kB     00:00     
extras/primary_db                                                                                 | 173 kB     00:00     
libselinux                                                                                        | 1.9 kB     00:00     
libselinux/primary_db                                                                             |  59 kB     00:00     
updates                                                                                           | 1.9 kB     00:00     
updates/primary_db                                                                                | 322 kB     00:00     
Reducing CentOS-5 - libselinux to included packages only
Finished
Enabling base-source repository
http://vault.centos.org/centos/5/os/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
Traceback (most recent call last):
  File "/usr/bin/yumdownloader", line 298, in ?
    util = YumDownloader()
  File "/usr/bin/yumdownloader", line 42, in __init__
    self.main()
  File "/usr/bin/yumdownloader", line 78, in main
    self.setupSourceRepos()
  File "/usr/bin/yumdownloader", line 118, in setupSourceRepos
    self._getSacks(archlist=archlist, thisrepo=repo.id)
  File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 502, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.4/site-packages/yum/repos.py", line 260, in populateSack
    sack.populate(repo, mdtype, callback, cacheonly)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 168, in populate
    if self._check_db_version(repo, mydbtype):
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 226, in _check_db_version
    return repo._check_db_version(mdtype)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1226, in _check_db_version
    repoXML = self.repoXML
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1399, in <lambda>
    repoXML = property(fget=lambda self: self._getRepoXML(),
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1395, in _getRepoXML
    raise Errors.RepoError, msg
yum.Errors.RepoError: Cannot retrieve repository metadata (repomd.xml) for repository: base-source. Please verify its path and try again
```

```
sed -i -e 's@/Source/@/SRPMS/@' /etc/yum.repos.d/CentOS-Sources.repo
yum clean all
yumdownloader --source php
```

works fine.

**Comment by tukiyo** [comment]
I tried 

```
yumdownloader --source php
```

then, error occured.

```
Loaded plugins: etckeeper, fastestmirror
Determining fastest mirrors
 * base: ftp.tsukuba.wide.ad.jp
 * extras: ftp.tsukuba.wide.ad.jp
 * libselinux: ftp.tsukuba.wide.ad.jp
 * updates: ftp.tsukuba.wide.ad.jp
base                                                                                              | 1.1 kB     00:00     
base/primary                                                                                      | 1.3 MB     00:00     
base                                                                                                           3667/3667
extras                                                                                            | 2.1 kB     00:00     
extras/primary_db                                                                                 | 173 kB     00:00     
libselinux                                                                                        | 1.9 kB     00:00     
libselinux/primary_db                                                                             |  59 kB     00:00     
updates                                                                                           | 1.9 kB     00:00     
updates/primary_db                                                                                | 322 kB     00:00     
Reducing CentOS-5 - libselinux to included packages only
Finished
Enabling base-source repository
http://vault.centos.org/centos/5/os/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
Traceback (most recent call last):
  File "/usr/bin/yumdownloader", line 298, in ?
    util = YumDownloader()
  File "/usr/bin/yumdownloader", line 42, in __init__
    self.main()
  File "/usr/bin/yumdownloader", line 78, in main
    self.setupSourceRepos()
  File "/usr/bin/yumdownloader", line 118, in setupSourceRepos
    self._getSacks(archlist=archlist, thisrepo=repo.id)
  File "/usr/lib/python2.4/site-packages/yum/__init__.py", line 502, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.4/site-packages/yum/repos.py", line 260, in populateSack
    sack.populate(repo, mdtype, callback, cacheonly)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 168, in populate
    if self._check_db_version(repo, mydbtype):
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 226, in _check_db_version
    return repo._check_db_version(mdtype)
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1226, in _check_db_version
    repoXML = self.repoXML
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1399, in <lambda>
    repoXML = property(fget=lambda self: self._getRepoXML(),
  File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1395, in _getRepoXML
    raise Errors.RepoError, msg
yum.Errors.RepoError: Cannot retrieve repository metadata (repomd.xml) for repository: base-source. Please verify its path and try again
```

```
sed -i -e 's@/Source/@/SRPMS/@' /etc/yum.repos.d/CentOS-Sources.repo
yum clean all
yumdownloader --source php
```

works fine.

**Comment by jperrin** [comment]
Hmm, interesting. that's a problem outside docker. I'll see that it gets raised. thanks.

**Comment by jperrin** [comment]
In theory this should be resolved now. Would you please try this again and report feedback?

**Comment by jperrin** [comment]
Resolved via symlink. Closing.
